### ISSUE TITLE
School board office code error

### ISSUE THREAD

**Issue by sgzasher** [justindbk/ceda#1]
Flagging tiny issue for public use -- small typo in recode_offname leaves it missing for all school board members. Should be "SCHOOL BOARD" instead of "SCHOOOL BOARD MEMBER". 

https://github.com/justindbk/ceda/blob/89b9c4d89a995444486852e8efbc4f6daeaad101/00-ceda_compile.R#L175

**Comment by justindbk** [comment]
This is now fixed in commit #dda0820b6185e5b733797cd29cee6b2223f2a036
